version: "3"

networks:
  internal:
    external: false

services:
  campus:
    image: theta:1.0.0
    build: .
    environment:
      - DATABASE_DB=theta_prod
      - DATABASE_HOST=db
    command: ./entrypoint.sh
    ports:
      - 4041:4041
    networks:
      - internal
    depends_on:
      - db

  db:
    image: postgres:12.3
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=theta_prod
    ports:
      - 5433:5432
    networks:
      - internal
